= Introducción
:description: This story chronicles the inexplicable hazards and vicious beasts a \
team must conquer and vanquish on their journey to discovering the true power of \
Open Source.

[example]
Lorem ipsum

[NOTE]
[caption="Nota"]
Lorem ipsum

[IMPORTANT]
[caption="Importante"]
Lorem ipsum

image::capsi.svg[]

image::gestion-nav-mapamind.svg[]

= Diagramas de casos de uso de negocio

== Control de acceso

=== Autenticación

image::login-business-usecase.svg[]
=== Reservar cita

image::citas-usecase.svg[]
=== Reservar prueba
image::pruebas-business-usecase.svg[]
=== Reservar consultorio
image::consultorios-business-usecase.svg[]
= Diagramas de casos de uso de aplicación
== Maestros
:toc:
=== Cita
:toc:
image::citas-app-usecase.svg[]
=== Prueba
image::pruebas-app-usecase.svg[]
=== Consultorio
image::consultorios-app-usecase.svg[]
=== Pacientes
image::pacientes-app-usecase.svg[]
=== Programas
image::programas-app-usecase.svg[]
=== Convenios
image::convenios-app-usecase.svg[]
=== Eps
image::eps-app-usecase.svg[]
=== Estados
image::estados-app-usecase.svg[]
=== Usuarios
image::usuarios-app-usecase.svg[]
=== Permisos
image::permisos-app-usecase.svg[]
