@startuml
left to right direction
actor Operador
actor Profesional

rectangle "Reservar cita" #BUSINESS {
  usecase "Registrar cita" as Citar
  usecase "Consultar agenda de profesional" as Agenda
    usecase "Administración de citas" as AdminCitas
  usecase "Consultar paciente" as ConsultarPaciente
  usecase "Registrar asistencia" as Asistencia
  usecase "Notificar a paciente" as NotificarPaciente
  usecase "Notificar a profesional" as NotificarProfesional
}
Operador -- AdminCitas
Operador -- Citar
Profesional -- Agenda
Operador -> Profesional
Citar <-. NotificarPaciente
Citar <-. NotificarProfesional
Citar -.> Agenda
Agenda <.- ConsultarPaciente
Agenda <.- Asistencia
AdminCitas <.-- Asistencia
@enduml