@startuml
actor/ Operador
actor/ Profesional
note as Nota
  Operador es relativo a
  Administrador o Auxiliar
end note
rectangle "Reserva de cita" #BUSINESS {
  package "Panel Operador" {
    usecase "Administración de citas" as AdminCitas << CRUD >>
    usecase/ "Registrar cita" as Citar
    usecase/ "Notificar a paciente" as NotificarPaciente
    usecase/ "Notificar a profesional" as NotificarProfesional
  }
  package "Panel Profesional" {
    usecase/ "Consultar agenda" as Agenda
    usecase "Consultar paciente" as ConsultarPaciente
    usecase/ "Registrar asistencia" as Asistencia
  }
}
Operador -- AdminCitas
Operador -- Citar
Profesional -- Agenda
Nota -> Operador
Operador -> Profesional
Citar -> AdminCitas
Citar <.. NotificarPaciente
Citar <.. NotificarProfesional
Agenda <.. ConsultarPaciente
Agenda <. Asistencia
Asistencia -.> AdminCitas
@enduml