@startmindmap
* Mascotas
** Perros
*** Pastor Alemán
*** Doberman
*** Pitbull
*** Gran Danés
** Peces
** Aves
** Conejos
** Gatos
*** <s>Angora</s> => Lorem
*** <s>Siames</s> => Lipsum
@endmindmap

@startmindmap
* Login
** Iniciar Secion
*** Autentica al usuario conforme al roll
** Registra contraseña
**Cerar sesion

@endmindmap