@startuml
left to right direction
actor Administrador
actor Auxiliar

rectangle Estado #Application {
  usecase "Insertar estado" as C
  usecase "Listar estados" as R
  usecase "Editar estado" as U
  usecase "Eliminar estado" as D
  usecase "Filtrar estados" as Searchable
  usecase "Ordenar estados" as Sortable
  usecase "Administrar estados" as CRUD
  note "Auxiliar puede o no realizar\r\n ciertas acciones de acuerdo\r\n al control de acceso" as Acl
}

CRUD <--. C
CRUD <--. R
CRUD <--. U

R <.. Searchable
R <.. Sortable
U <.. D: "Eliminar un estado"
R <.. D: "Eliminar varios estados"

Administrador --> CRUD
Auxiliar --> CRUD
Acl -> CRUD
@enduml