@startmindmap
* Gestión
** Reservas
*** Citas
*** Pruebas
*** Consultorios
** Maestros
*** Pacientes
*** Consultorios
*** Pruebas
*** Programas
*** Convenios
*** Eps
*** Estados
** Seguridad
*** Usuarios
*** Permisos
@endmindmap

