@startuml
left to right direction
actor Administrador
actor Auxiliar
actor Profesional
rectangle Login #BUSINESS {
  usecase "Iniciar sesión" as Auth
  usecase "Acceso Panel Profesional" as PanelProfesional
  usecase "Acceso Panel Gestión" as PanelAdmin
  usecase "Credenciales inválidas" as FailAuth
  note "Dependerá del nivel del usuario\r\nDeterminar el panel correspondiente" as Condition
}
Auth <.- FailAuth
Auth --> PanelProfesional
Auth --> PanelAdmin
Auth -> Condition
Administrador -- Auth
Auxiliar -- Auth
Profesional -- Auth
@enduml