@startuml
left to right direction
actor Administrador
actor Auxiliar

rectangle Paciente {  
  usecase "Administrar paciente" as CRUD
  usecase "Insertar paciente" as C
  usecase "Listar pacientes" as R
  usecase "Editar paciente" as U
  usecase "Borrar paciente" as D
  usecase "Filtrar paciente" as Searchable
  usecase "Ordenar paciente" as Sortable
  usecase "Borrar múltiples pacientes" as Bulk
  note "Auxiliar puede o no realizar\r\n ciertas acciones de acuerdo\r\n al control de acceso" as Acl
}
CRUD --> C
CRUD --> R
CRUD --> U
CRUD --> D

R --> Searchable
R --> Sortable
R -.> Bulk: "A discreción"
U .> D: "Eliminar algún paciente"

Administrador --> CRUD
Auxiliar --> CRUD
Acl -> CRUD
@enduml