@startuml
participant Profesional
boundary "Panel de profesional" as Panel
control Agenda
entity Cita
database Consultorio

Profesional -> Panel : Profesional revisa citas
Panel -> Agenda : Asistencia de paciente
Agenda -> Panel: Registrar que el paciente no asistió
Agenda -> Cita: Registrar que el paciente asistió
Cita -> Consultorio: Asistir al paciente
Consultorio -> Profesional: Atender al paciente y registra el resultado
@enduml