= Introducción
:doctype: book
:toc: 

[example]
Lorem ipsum

[NOTE]
[caption="Nota"]
Lorem ipsum

[IMPORTANT]
[caption="Importante"]
Lorem ipsum

image::capsi.svg[]

image::gestion-nav-mapamind.svg[]

= Diagramas de casos de uso de negocio
:doctype: book
:toc: 
== Control de acceso
:doctype: book
:toc: 
=== Autenticación
:doctype: book
:toc: 
image::login-business-usecase.svg[]
=== Reservar cita
:doctype: book
:toc: 
image::citas-usecase.svg[]
=== Reservar prueba
image::pruebas-business-usecase.svg[]
=== Reservar consultorio
image::consultorios-business-usecase.svg[]
= Diagramas de casos de uso de aplicación
== Maestros
=== Cita
image::citas-app-usecase.svg[]
=== Prueba
image::pruebas-app-usecase.svg[]
=== Consultorio
image::consultorios-app-usecase.svg[]
=== Pacientes
image::pacientes-app-usecase.svg[]
=== Programas
image::programas-app-usecase.svg[]
=== Convenios
image::convenios-app-usecase.svg[]
=== Eps
image::eps-app-usecase.svg[]
=== Estados
image::estados-app-usecase.svg[]
=== Usuarios
image::usuarios-app-usecase.svg[]
=== Permisos
image::permisos-app-usecase.svg[]
