@startuml
left to right direction
actor Administrador
actor Auxiliar

rectangle Cita #BUSINESS {
  usecase "Insertar cita" as C
  usecase "Listar citas" as R
  usecase "Editar cita" as U
  usecase "Eliminar cita" as D
  usecase "Filtrar citas" as Searchable
  usecase "Ordenar citas" as Sortable
  usecase "Administrar citas" as CRUD
  note "Auxiliar puede o no realizar\r\n ciertas acciones de acuerdo\r\n al control de acceso" as Acl
}

CRUD <--. C
CRUD <--. R
CRUD <--. U

R <.. Searchable
R <.. Sortable
U <.. D: "Eliminar un cita"
R <.. D: "Eliminar varios citas"

Administrador -- CRUD
Auxiliar -- CRUD
Acl - CRUD
@enduml