@startuml
left to right direction
actor Administrador
actor Auxiliar

rectangle Paciente #Application {
  usecase "Insertar paciente" as C
  usecase "Listar pacientes" as R
  usecase "Editar paciente" as U
  usecase "Eliminar paciente" as D
  usecase "Filtrar pacientes" as Searchable
  usecase "Ordenar pacientes" as Sortable
  usecase "Administrar pacientes" as CRUD
  note "Auxiliar puede o no realizar\r\n ciertas acciones de acuerdo\r\n al control de acceso" as Acl
}

CRUD <--. C
CRUD <--. R
CRUD <--. U

R <.. Searchable
R <.. Sortable
U <.. D: "Eliminar un paciente"
R <.. D: "Eliminar varios pacientes"

Administrador -- CRUD
Auxiliar -- CRUD
Acl - CRUD
@enduml